"""Gaussian optics in PGA2D: a thin lens is a linear map on lines, so it is an extensor.

A ray is a line. A thin lens of focal length `focal` at the origin sends the line
`a * mv.x + b * mv.y + c * mv.w` to `(a - c / focal) * mv.x + b * mv.y + c * mv.w`, which is
`Line - (Line & origin) * (mv.x / focal)` with the line left open. A lens elsewhere is that map
conjugated by a translator, and a system of lenses is a composition. Lines are global, so the
free space between elements needs no map of its own.

In ray-transfer optics a ray reads as its height and slope where it crosses one reference plane,
each element as an ABCD matrix on that pair, and the free space between elements as a
propagation matrix of its own.
"""

from __future__ import annotations

from numga import NumpyContext, stack
from numga.algebras import PGA2D

ga = PGA2D
ctx = NumpyContext(ga)
mv = ctx.multivector
Line = ga.gatype.vector()
Point = ga.gatype.antivector()
LineMap = ga.gatype((Line, Line))
Motor = ga.gatype.rotor()

origin: Point = mv.xy
# Every train element is defined in the plane x == 0.
home: Line = mv.x


def point(x: float, y: float) -> Point:
    """The point at (x, y): the meet of the vertical and horizontal lines through it."""
    return (mv.x - mv.w * x) ^ (mv.y - mv.w * y)


def thin_lens(plane: Line, focal: float) -> LineMap:
    """A thin lens in a vertical plane, as a map on lines.

    At the origin it shears a line's x coefficient by the line's incidence with the origin over
    the focal length. Anywhere else it is that map conjugated by the translator onto its plane,
    generated by the ideal point along y scaled by the plane's offset from the origin.
    """
    shear: LineMap = Line - (Line & origin) * (mv.x / focal)
    shift: Motor = (mv.wx * (plane & origin) * 0.5).exp()
    return shift >> shear(shift << Line)


# An optical train in the abstract. Every element is a map on lines defined in the home plane:
# a thin lens shears a line by its incidence with the centre, a thin prism by its incidence
# with an ideal point (the same slope change for every height), and a flat mirror is the
# sandwich by the home plane.
ELEMENTS: tuple[LineMap, ...] = (
    # A thin lens of focal length 1.
    Line - (Line & origin) * (home / 1.0),
    # A thin prism, slope change 0.15.
    Line - (Line & mv.wx) * home * 0.15,
    # A thin lens of focal length -2.
    Line - (Line & origin) * (home / -2.0),
    # A flat mirror in the home plane.
    home.normalized() >> Line,
)


def trace(rays: Line, motors: tuple[Motor, ...], elements: tuple[LineMap, ...]):
    """Place each element by its motor and pass the bundle through the train.

    Returns the element planes [element], the bundle before and after each element
    [element + 1, ray], and the train: the composition of the placed elements, one map on
    lines that acts on the whole bundle.
    """
    train: LineMap = mv.rotor() >> Line
    legs = [rays]
    for motor, element in zip(motors, elements):
        # The element conjugated into place, the bundle after it, and the train so far as one map.
        placed: LineMap = motor >> element(motor << Line)   # [] Line <- Line
        rays = placed(rays)                                 # [ray] Line
        train = placed(train)                               # [] Line <- Line
        legs.append(rays)
    return stack([motor >> home for motor in motors]), stack(legs), train
