"""Pure PGA3D scenegraph, robot kinematics, and compound multi-lens camera optics.

All mathematical operations are formulated as coordinate-free extensors (linear maps
between blade subspaces). The entire visual pipeline—articulated forward kinematics,
anisotropic box scaling, camera pose transformation, pupil ray formation, compound
two-lens refraction, sensor plane intersection, and viewport rasterization—collapses
into a single compiled extensor mapping canonical unit box vertices to 2D screen pixels.
"""

from __future__ import annotations

import numpy as np

from numga import NumpyContext, stack
from numga.algebras import PGA3D

# --- algebra context and types --------------------------------------------------------
ga = PGA3D
ctx = NumpyContext(ga)
mv = ctx.multivector

# Blade subspaces:
Scalar = ga.gatype.scalar()                 # Grade 0: scalar values
Plane = ga.gatype.vector()                  # Grade 1: planes in 3D (x, y, z, w)
Line = ga.gatype.bivector()                 # Grade 2: lines in 3D / twists in se(3)
Point = ga.gatype.antivector()              # Grade 3: projective points (zyx, yzw, zxw, xyw)
Motor = ga.gatype.rotor()                   # Even subalgebra: rigid transformations in SE(3)

# Extensors (linear maps between blade subspaces):
PointMap = ga.gatype((Point, Point))        # Collineation: Point <- Point
LineMap = ga.gatype((Line, Line))           # Optical ray transfer map: Line <- Line
RayProjector = ga.gatype((Line, Point))     # Ray constructor: Line <- Point
SensorIntersection = ga.gatype((Point, Line)) # Sensor plane meet: Point <- Line


# --- geometry primitives --------------------------------------------------------------
def canonical_unit_box() -> Point:
    """Return the 8 vertices of the canonical unit box [-0.5, 0.5]^3 as a Point multivector."""
    # Homogeneous coordinates [x, y, z, weight]:
    return mv.antivector([
        [-0.5, -0.5, -0.5, 1.0],
        [ 0.5, -0.5, -0.5, 1.0],
        [ 0.5,  0.5, -0.5, 1.0],
        [-0.5,  0.5, -0.5, 1.0],
        [-0.5, -0.5,  0.5, 1.0],
        [ 0.5, -0.5,  0.5, 1.0],
        [ 0.5,  0.5,  0.5, 1.0],
        [-0.5,  0.5,  0.5, 1.0],
    ])


def unit_box_topology() -> tuple[np.ndarray, np.ndarray]:
    """Return (edges, faces) vertex index arrays for the unit box."""
    edges = np.array([
        [0, 1], [1, 2], [2, 3], [3, 0],  # bottom ring (z = -0.5)
        [4, 5], [5, 6], [6, 7], [7, 4],  # top ring (z = +0.5)
        [0, 4], [1, 5], [2, 6], [3, 7],  # vertical pillars
    ], dtype=np.int32)

    faces = np.array([
        [0, 1, 2, 3],  # bottom (-z)
        [4, 5, 6, 7],  # top (+z)
        [0, 1, 5, 4],  # front (-y)
        [2, 3, 7, 6],  # back (+y)
        [0, 3, 7, 4],  # left (-x)
        [1, 2, 6, 5],  # right (+x)
    ], dtype=np.int32)

    return edges, faces


# --- affine and kinematic maps --------------------------------------------------------
def make_anisotropic_scale(scale_x: float, scale_y: float, scale_z: float = 1.0) -> PointMap:
    """Anisotropic scaling extensor (Point <- Point) along principal axes.

    Constructed directly as an extensor from a diagonal matrix over the Point subspace.
    """
    return ctx.extensor(PointMap, np.diag([scale_x, scale_y, scale_z, 1.0]))


def make_translator(displacement_x: float, displacement_y: float, displacement_z: float) -> Motor:
    """Translation motor in SE(3) generated by the ideal bivectors xw, yw, zw."""
    bivector_generator = (
        mv.xw * (displacement_x * 0.5)
        + mv.yw * (displacement_y * 0.5)
        + mv.zw * (displacement_z * 0.5)
    )
    return bivector_generator.exp()


def make_rotor_x(angle_radians: float) -> Motor:
    """Rotation motor in SE(3) around the local x-axis (yz-plane rotation)."""
    return (mv.yz * (angle_radians * 0.5)).exp()


def make_rotor_y(angle_radians: float) -> Motor:
    """Rotation motor in SE(3) around the local y-axis (zx-plane rotation)."""
    return (mv.zx * (angle_radians * 0.5)).exp()


def make_rotor_z(angle_radians: float) -> Motor:
    """Rotation motor in SE(3) around the local z-axis (xy-plane rotation)."""
    return (mv.xy * (angle_radians * 0.5)).exp()


# --- articulated robot arm forward kinematics -----------------------------------------
def make_robot_arm(
    joint_angles: tuple[float, float, float, float] = (0.35, -0.45, 0.85, -0.40),
) -> tuple[PointMap, list[Motor]]:
    """Construct forward kinematics extensors for a 5-body articulated robot arm.

    All bodies originate from the canonical unit box [-0.5, 0.5]^3 and are shaped by
    anisotropic scaling extensors, then placed into world coordinates by cumulative
    joint motors.

    Parameters
    ----------
    joint_angles : tuple of 4 floats
        (base_yaw, shoulder_pitch, elbow_pitch, wrist_pitch) in radians.

    Returns
    -------
    bodies_to_world : PointMap of shape (5,)
        Batched extensor mapping canonical unit box points to world points for each body.
    joint_pivots : list of 4 Motors
        World placement motors of the revolute joint pivots for visualization.
    """
    theta_base, theta_shoulder, theta_elbow, theta_wrist = joint_angles

    # Body 0: Base pedestal (fixed stationary block resting on floor z = 0)
    scale_base = make_anisotropic_scale(0.9, 0.9, 0.25)
    pose_base = make_translator(0.0, 0.0, 0.125)
    body_0 = pose_base >> scale_base

    # Turret base pivot at z = 0.25, yawing around vertical z-axis:
    pivot_turret = make_translator(0.0, 0.0, 0.25) * make_rotor_z(theta_base)

    # Body 1: Turret rotating body
    scale_turret = make_anisotropic_scale(0.5, 0.5, 0.35)
    pose_turret = pivot_turret * make_translator(0.0, 0.0, 0.175)
    body_1 = pose_turret >> scale_turret

    # Shoulder pivot at z = 0.35 above turret base, pitching around local y-axis:
    pivot_shoulder = pivot_turret * make_translator(0.0, 0.0, 0.35) * make_rotor_y(theta_shoulder)

    # Body 2: Upper arm (anisotropically elongated along arm length)
    scale_upper = make_anisotropic_scale(0.24, 0.24, 1.2)
    pose_upper = pivot_shoulder * make_translator(0.0, 0.0, 0.6)
    body_2 = pose_upper >> scale_upper

    # Elbow pivot at tip of upper arm (1.2 units along upper arm), pitching around local y-axis:
    pivot_elbow = pivot_shoulder * make_translator(0.0, 0.0, 1.2) * make_rotor_y(theta_elbow)

    # Body 3: Forearm (anisotropically elongated along forearm length)
    scale_forearm = make_anisotropic_scale(0.18, 0.18, 1.0)
    pose_forearm = pivot_elbow * make_translator(0.0, 0.0, 0.5)
    body_3 = pose_forearm >> scale_forearm

    # Wrist pivot at tip of forearm (1.0 units along forearm), pitching around local y-axis:
    pivot_wrist = pivot_elbow * make_translator(0.0, 0.0, 1.0) * make_rotor_y(theta_wrist)

    # Body 4: Gripper tool block / end-effector
    scale_gripper = make_anisotropic_scale(0.28, 0.14, 0.3)
    pose_gripper = pivot_wrist * make_translator(0.0, 0.0, 0.15)
    body_4 = pose_gripper >> scale_gripper

    # Stack all 5 body extensors into a single batched extensor:
    bodies_to_world = stack([body_0, body_1, body_2, body_3, body_4])
    joint_pivots = [pivot_turret, pivot_shoulder, pivot_elbow, pivot_wrist]

    return bodies_to_world, joint_pivots


def make_thin_lens(
    center: Point = mv.zyx,
    plane: Plane = -mv.z,
    focal_length: float = 1.0,
) -> LineMap:
    """Construct a thin lens extensor (Line <- Line) focusing rays towards its center."""
    return Line - (center & (Line ^ plane)) / focal_length


# --- compound multi-lens camera optics ------------------------------------------------
def make_multi_lens_camera(
    camera_pose: Motor,
    focal_front: float = 1.0,
    focal_rear: float = 0.8,
    rear_gap: float = -0.3,
    pupil_radius: float = 0.02,
    sensor_distance: float = 1.25,
) -> PointMap:
    """Construct a compound multi-lens camera extensor mapping 3D world points to 3D sensor points.

    Following Gaussian optics in PGA, each thin lens shears a line proportionally to its
    incidence with the optical center: Line - (center & (Line ^ plane)) / f.
    A compound optical system is simply the functional composition of the lens extensors:
    optics = rear_lens(front_lens).
    The rear lens is placed along the optical axis by transforming it with its displacement motor:
    rear_lens = rear_placement >> base_rear_lens(rear_placement << Line).

    Parameters
    ----------
    camera_pose : Motor
        Rigid placement of the camera body in world space.
    focal_front : float
        Focal length of the front objective lens (default: 1.0).
    focal_rear : float
        Focal length of the rear relay/focusing lens (default: 0.8).
    rear_gap : float
        Axial displacement of the rear lens behind the front lens along z (default: -0.3).
    pupil_radius : float
        Off-center pupil sample displacement on the entrance aperture (default: 0.02).
    sensor_distance : float
        Axial distance of the sensor plane behind the front lens along -z (default: 1.25).

    Returns
    -------
    camera : PointMap
        Single compiled extensor: Point <- Point.
    """
    front_center = mv.zyx
    front_plane = -mv.z

    # Front lens at origin:
    front_lens = make_thin_lens(front_center, front_plane, focal_front)

    # Rear lens: transform the lens extensor directly by axial displacement motor:
    rear_placement = make_translator(0.0, 0.0, rear_gap)
    base_rear_lens = make_thin_lens(front_center, front_plane, focal_rear)
    rear_lens = rear_placement >> base_rear_lens(rear_placement << Line)

    # Compound optical train: functional composition of the two lens extensors (Line <- Line):
    optics = rear_lens(front_lens)

    # Pupil point on the entrance pupil aperture (offset from optical center to induce bending):
    pupil = (mv.xw * pupil_radius).exp() >> front_center

    # Transform world points into local camera space, then join with pupil to form rays:
    world_to_camera = camera_pose << Point
    incoming_rays = world_to_camera & pupil   # Line <- Point

    # Sensor plane at z = -sensor_distance: plane equation z + sensor_distance * w = 0
    sensor_plane = mv.z + sensor_distance * mv.w
    to_sensor = Line ^ sensor_plane          # Point <- Line

    # Compose into single camera extensor: Point <- Point
    camera = to_sensor(optics(incoming_rays))
    return camera


def make_camera_pose(
    position: tuple[float, float, float] = (0.0, -3.6, 1.3),
    target: tuple[float, float, float] = (0.0, 0.0, 1.18),
) -> Motor:
    """Construct camera motor in world space pointing along optical axis -z towards target."""
    px, py, pz = position
    tx, ty, tz = target
    displacement = make_translator(px, py, pz)

    # Calculate pitch angle to tilt optical axis -z from horizontal towards target:
    delta_y = ty - py
    delta_z = tz - pz
    pitch = np.arctan2(delta_z, delta_y)
    # Rotate around x-axis: pi/2 turns -z forward (+y), minus pitch tilts downward
    orientation = make_rotor_x(np.pi * 0.5 - pitch)

    return displacement * orientation


# --- viewport and scenegraph collapse -------------------------------------------------
def make_viewport(
    width: int = 640,
    height: int = 480,
    sensor_width: float = 1.6,
    sensor_height: float = 1.2,
    scale_pixels_per_unit: float | None = None,
) -> PointMap:
    """Viewport extensor mapping metric sensor coordinates (x, y) to pixel coordinates (u, v).

    The physical sensor (sensor_width x sensor_height) is mapped to (width x height) pixels.
    Because raster pixel rows increase downward (y=0 at top), the vertical axis is reflected.
    """
    if scale_pixels_per_unit is not None:
        scale_x = scale_pixels_per_unit
        scale_y = scale_pixels_per_unit
    else:
        scale_x = width / sensor_width
        scale_y = height / sensor_height
    scale = make_anisotropic_scale(scale_x, -scale_y, 1.0)
    translation = make_translator(width * 0.5, height * 0.5, 0.0)
    return translation >> scale


def collapse_scenegraph(
    bodies_to_world: PointMap,
    camera: PointMap,
    viewport: PointMap,
) -> PointMap:
    """Collapse the entire graphics pipeline into a single compiled extensor.

    The composition chain:
    canonical unit box => anisotropic body scaling => joint motors => world coordinates
    => camera pose => entrance pupil ray => front lens refraction => rear lens refraction
    => sensor plane intersection => 2D viewport pixel rasterization.

    Returns
    -------
    local_to_pixel : PointMap of shape (num_bodies,)
        Single compiled extensor: Point <- Point.
    """
    return viewport(camera(bodies_to_world))


def project_vertices(local_to_pixel: PointMap, unit_box: Point) -> Point:
    """Batch-project canonical unit box vertices directly to screen pixels.

    Parameters
    ----------
    local_to_pixel : PointMap of shape (num_bodies,)
    unit_box : Point of shape (8,)

    Returns
    -------
    normalized_pixels : Point of shape (num_bodies, 8)
        Homogeneous screen points with unit weight (mv.w & p == 1).
    """
    # Batched extensor evaluation with broadcasting:
    raw_pixels = local_to_pixel[:, None](unit_box[None, :])
    # Perspective normalization:
    return raw_pixels / (mv.w & raw_pixels)


# --- 3D optical ray tracing -----------------------------------------------------------
def trace_sample_rays(
    scene_points: Point,
    camera_pose: Motor,
    focal_front: float = 1.0,
    focal_rear: float = 0.8,
    rear_gap: float = -0.3,
    pupil_radius: float = 0.02,
    sensor_distance: float = 1.25,
) -> list[tuple[Point, Point, Point, Point]]:
    """Trace exact 3D ray paths from scene points through the compound optical train to the sensor.

    Returns
    -------
    ray_stages : list of tuples (p_scene_world, p_front_world, p_rear_world, p_sensor_world)
        Exact 3D coordinates at each optical interface in world space.
    """
    front_center = mv.zyx
    front_plane = -mv.z
    sensor_plane = mv.z + sensor_distance * mv.w

    rear_placement = make_translator(0.0, 0.0, rear_gap)
    rear_plane = rear_placement >> front_plane

    front_lens = make_thin_lens(front_center, front_plane, focal_front)
    base_rear_lens = make_thin_lens(front_center, front_plane, focal_rear)
    rear_lens = rear_placement >> base_rear_lens(rear_placement << Line)

    pupil_local = (mv.xw * pupil_radius).exp() >> front_center

    stages = []
    # Loop over individual scene points algebraically:
    num_points = scene_points.shape[0] if scene_points.shape else 1
    pts = [scene_points[i] for i in range(num_points)] if scene_points.shape else [scene_points]

    for p_world in pts:
        p_cam = camera_pose << p_world
        ray_in = p_cam & pupil_local
        p_front_cam = pupil_local

        # Refraction through front lens:
        ray_mid = front_lens(ray_in)
        p_rear_cam = ray_mid ^ rear_plane
        p_rear_cam = p_rear_cam / (mv.w & p_rear_cam)

        # Refraction through rear lens:
        ray_out = rear_lens(ray_mid)
        p_sensor_cam = ray_out ^ sensor_plane
        p_sensor_cam = p_sensor_cam / (mv.w & p_sensor_cam)

        # Transform all points back to world space:
        p_front_world = camera_pose >> p_front_cam
        p_rear_world = camera_pose >> p_rear_cam
        p_sensor_world = camera_pose >> p_sensor_cam

        stages.append((p_world, p_front_world, p_rear_world, p_sensor_world))

    return stages


# --- verification checks --------------------------------------------------------------
def run_checks() -> None:
    """Kernel-level assertions verifying algebraic correctness."""
    unit_box = canonical_unit_box()

    # 1. Anisotropic scaling extensor check:
    sx, sy, sz = 2.5, 0.4, 1.8
    scale = make_anisotropic_scale(sx, sy, sz)
    sample_pt = mv.antivector([1.0, 2.0, 3.0, 1.0])
    scaled_pt = scale(sample_pt)
    np.testing.assert_allclose(
        scaled_pt.kernel,
        [1.0 * sx, 2.0 * sy, 3.0 * sz, 1.0],
        atol=1e-12,
        err_msg="Anisotropic scale extensor failed coordinate test",
    )

    # 2. Kinematic chain shape check:
    bodies_to_world, joint_pivots = make_robot_arm()
    assert bodies_to_world.shape == (5,), "Expected 5 stacked body extensors"
    assert len(joint_pivots) == 4, "Expected 4 joint pivot motors"

    # 3. Multi-lens camera and viewport pipeline composition check:
    camera_pose = make_camera_pose()
    camera = make_multi_lens_camera(camera_pose)
    viewport = make_viewport()

    # Check that sequential application matches compiled pipeline:
    local_to_pixel = collapse_scenegraph(bodies_to_world, camera, viewport)
    assert local_to_pixel.shape == (5,), "Collapsed extensor must preserve body batch shape"

    # Evaluate sequentially vs compiled on unit_box:
    for body_index in range(5):
        single_body = bodies_to_world[body_index]
        compiled_body_to_pixel = local_to_pixel[body_index]

        pts_world = single_body(unit_box)
        pts_sensor = camera(pts_world)
        pts_pixel_sequential = viewport(pts_sensor)
        pts_pixel_sequential_norm = pts_pixel_sequential / (mv.w & pts_pixel_sequential)

        pts_pixel_compiled = compiled_body_to_pixel(unit_box)
        pts_pixel_compiled_norm = pts_pixel_compiled / (mv.w & pts_pixel_compiled)

        np.testing.assert_allclose(
            pts_pixel_sequential_norm.kernel,
            pts_pixel_compiled_norm.kernel,
            atol=1e-10,
            err_msg=f"Pipeline collapse mismatch for body {body_index}",
        )

    # 4. Batched evaluation check:
    batch_projected = project_vertices(local_to_pixel, unit_box)
    assert batch_projected.shape == (5, 8), "Batch projection must produce (5, 8) screen points"
    # Verify screen weights are all 1.0:
    weights = (mv.w & batch_projected).kernel
    np.testing.assert_allclose(weights, 1.0, atol=1e-12, err_msg="Perspective normalization failed")
