"""Gaussian optics in PGA2D: a thin lens is a linear map on lines, so it is an extensor.

A ray is a line, not a height and a slope at some reference plane. A thin lens of focal
length f at the origin sends the line a x + b y + c w to (a - c/f) x + b y + c w, which is
Line - (Line ∨ origin) x / f with the line left open. A lens elsewhere is that map conjugated
by a translator, and a system of lenses is a composition. There is no free-space propagation
matrix, because lines are already global; ABCD matrices are what you get when you insist on
describing a line by where it crosses one particular plane.
"""

from __future__ import annotations

from numga import NumpyContext, stack
from numga.algebras import PGA2D

ga = PGA2D
ctx = NumpyContext(ga)
mv = ctx.multivector
Line = ga.gatype.vector()
Point = ga.gatype.antivector()
LineMap = ga.gatype((Line, Line))
Motor = ga.gatype.rotor()

origin: Point = mv.xy
home: Line = mv.x                                   # every train element is defined in the plane x = 0


def point(x: float, y: float) -> Point:
    """The point at (x, y): the meet of the vertical and horizontal lines through it."""
    return (mv.x - mv.w * x) ^ (mv.y - mv.w * y)


def thin_lens(plane: Line, focal: float) -> LineMap:
    """A thin lens in a vertical plane, as a map on lines.

    At the origin it shears a line's x coefficient by the line's incidence with the origin over
    the focal length. Anywhere else it is that map conjugated by the translator onto its plane,
    generated by the ideal point along y scaled by the plane's offset from the origin.
    """
    shear: LineMap = Line - (Line & origin) * (mv.x / focal)
    shift: Motor = (mv.wx * (plane & origin) * 0.5).exp()
    return shift >> shear(shift << Line)


# An optical train in the abstract. Every element is a map on lines defined in the home plane:
# a thin lens shears a line by its incidence with the centre, a thin prism by its incidence
# with an ideal point (the same slope change for every height), and a flat mirror is the
# sandwich by the home plane.
ELEMENTS: tuple[LineMap, ...] = (
    Line - (Line & origin) * (home / 1.0),          # thin lens, f = 1
    Line - (Line & mv.wx) * home * 0.15,            # thin prism, slope change 0.15
    Line - (Line & origin) * (home / -2.0),         # thin lens, f = -2
    home.normalized() >> Line,                      # flat mirror in the home plane
)


def trace(rays: Line, motors: tuple[Motor, ...], elements: tuple[LineMap, ...]):
    """Place each element by its motor and pass the bundle through the train.

    Returns the element planes [element], the bundle before and after each element
    [element + 1, ray], and the train: the composition of the placed elements, one map on
    lines that acts on the whole bundle.
    """
    train: LineMap = mv.rotor() >> Line
    legs = [rays]
    for motor, element in zip(motors, elements):
        placed: LineMap = motor >> element(motor << Line)   # the element conjugated into place
        rays = placed(rays)                                 # the bundle after this element
        train = placed(train)                               # the train so far, as one map
        legs.append(rays)
    return stack([motor >> home for motor in motors]), stack(legs), train
